### ISSUE TITLE
Wordpress admin dashboard no longer working (Custom Login latest, WP 4.2.2)

### ISSUE THREAD

**Issue by mtressl** [thefrosty/custom-login#11]
I realized that my admin dashboard lost drag/drop functionality, also the screen options menu was no longer clickable.
So I disabled all extensions and added one by one, always testing the admin dashboard.

-> problem is the Custom Login plugin.
Can you please fix this?

**Comment by thefrosty** [comment]
I was not aware of this issue, but know of some bugs in the dashboard widget(s). I'm working on a fix but have not had the time to push out a new version.

**Comment by mtressl** [comment]
Thank you, waiting for the fix.
