### ISSUE TITLE
Re-direct after Login

### ISSUE THREAD

**Issue by Llurendt** [thefrosty/custom-login#14]
Hello! How do you change the re-direct link after login is completed? It currently re-directs to a page which says the forum is offline... I'd like to modify the link somehow.

Thanks!
Llurendt

**Comment by Llurendt** [comment]
What I want to do is simply have ALL logins be directed to a single place. It is currently re-directing to a forum which no longer exists.

**Comment by thefrosty** [comment]
Please refer to this extension to handle custom redirects: https://frosty.media/plugins/custom-login-redirects/
