### ISSUE TITLE
Login does not function when using blog in a page

### ISSUE THREAD

**Issue by ErnstOpusVDesign** [thefrosty/custom-login#17]
We have a Dutch website with special pages for members.
We are using your code on pages where also newsitems are shown in a Post Masonry Grid.
Page is divided in two parts, upper part for everyone, down for members!

The newsitems are for members only but still shown on the page: http://www.emdr.nl/speciaal-voor-leden/
What can we do to solve this?

Kind Regards,

Angèle

**Comment by thefrosty** [comment]
I am sorry, this plugin doesn't hide content for users, it's simply a means to customize your `/wp-login.php` page.
