### ISSUE TITLE
Custom HTML causes Google Tag Manager script to fial

### ISSUE THREAD

**Issue by mikeg-de** [thefrosty/custom-login#23]
The `<noscript`> tag is flagged as not being closed despite being valid. Though, I think for that reason the `<script>(function(…` part is getting parsed wrong resulting in the function code being displayed as text.

Edit: Removing the noscript tags results in stripping away the iframe

**Comment by thefrosty** [comment]
You're trying to paste an iframe into the custom HTML field?

**Comment by mikeg-de** [comment]
Please find as follows the original code provided by Google:

`
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MMQ5VT"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MMQ5VT');</script>
`

**Comment by thefrosty** [comment]
That kind of code isn't supported and could be considered malicious. If you want to add that you'd have to do so in your theme or a custom plugin.
