### ISSUE TITLE
Api calls to https://frosty.media/feed (even when Dashboard widget is off) slowing down wp login

### ISSUE THREAD

**Issue by remcokalf** [thefrosty/custom-login#35]
Sometimes when logging into WP, it takes long. I checked api calls with QueryMonitor plugin and noticed that one of the long API calls is from Custom Login. It is checking https://frosty.media/feed, and it took almost 1.5 seconds, with a timeout of 10s.

![Schermafbeelding 2020-01-31 om 14 20 43](https://user-images.githubusercontent.com/4609920/73542812-d4a8a900-4435-11ea-99e5-c9b8f5f7e786.png)

As far as I can tell, this feed url is only used in Dashboard.php.
But I have the Dashboard widget turned off in the General settings.

Could you just not load dashboard.php when it is not needed?
Maybe I am missing something but this api call is slowing login times unnecessarily, even when it is not needed.

**Comment by thefrosty** [comment]
Thanks for the issue. That definitely shouldn't be making calls when the dashboard widget is off. I'm not sure on the timeline to get a fix in, but PR's are open if you happen to push one.
