### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by intellectualamoeba** [thefrosty/custom-login#7]
plugin deployed on test site works, with custom logo and shadows switched off. When installed on main site, with the exact same settings, I can only see the default WP login and forgot password page, not the page im expecting to see.

Attached are screenshots from the staging as well as development sites, with the difference.

Wordpress 4.2.1
![main_site](https://cloud.githubusercontent.com/assets/3201776/7496650/54d11e1a-f40d-11e4-8da6-ac51b18417d2.PNG)
![staging_site](https://cloud.githubusercontent.com/assets/3201776/7496654/57f0956c-f40d-11e4-9661-19bc997c3878.PNG)

**Comment by thefrosty** [comment]
Can you provide a link to the site? It's hard to know what's happening with just a screenshot.

**Comment by intellectualamoeba** [comment]
Hi,

It's http://twobigears.com/store

This is an ecommerce setup so you won't see anything when you go the above link. Best way is to check the forgot password link on
http://twobigears.com/store/wp-login.php

The site that works is

http://staging.twobigears.com/wp-login.php

**Comment by Tranest8tion** [comment]
Using Custom Login Version 3.2.4 on WordPress 4.3.1, and using ArkaHost theme, the Custom Login does not work at all, period. I dont know what is causing this, but it has worked on every other site except this one. The website URL is:

https://www.hostbuilder.website/wp-login.php

Any and all help is appreciated.

Thanks

Webmaster
