### ISSUE TITLE
Does not work with custom stealthed login url

### ISSUE THREAD

**Issue by WSP-webmaster** [thefrosty/custom-login#9]
I have a stealthed custom login url already and the plugin does not load.

Please add a input field to specify the login url if one exists.

No .php is at the end of the url

example of login url     www.siteA.com/mylogin/

**Comment by thefrosty** [comment]
Is the _stealth_ URL a rewrite of `wp-login.php`? If not this is expected behavior. Custom Login only outputs its data to the wp-login.php page hooks.
